# Generated by Django 5.2.3 on 2025-07-15 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blogpost_category_blogpost_comments_blogpost_likes_and_more"),
        ("members", "0006_alter_userprofile_rank"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="comments",
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "commentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.userprofile",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="blog.blogpost",
                    ),
                ),
            ],
        ),
    ]
