# Generated by Django 5.2.3 on 2025-07-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_blogpost_options_alter_comment_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("technology", "Technology"),
                    ("sports", "Sports"),
                    ("health", "Health"),
                    ("travel", "Travel"),
                    ("food", "Food"),
                    ("entertainment", "Entertainment"),
                    ("education", "Education"),
                    ("business", "Business"),
                    ("lifestyle", "Lifestyle"),
                    ("news", "News"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
