# Generated by Django 5.2.3 on 2025-07-16 05:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_blogpost_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="view_count",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="views",
            field=models.ManyToManyField(
                blank=True, related_name="views", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
