# Generated by Django 5.2.3 on 2025-07-21 11:40

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_rename_content_comment_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=blog.models.user_directory_path
            ),
        ),
    ]
