# Generated by Django 5.2.3 on 2025-07-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_userprofile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/profile_pics/"
            ),
        ),
    ]
