# Generated by Django 5.2.3 on 2025-07-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_alter_userprofile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="rank",
            field=models.CharField(
                choices=[("author", "Author"), ("reader", "Reader")],
                default="reader",
                max_length=20,
            ),
        ),
    ]
