# Generated by Django 5.2.3 on 2025-07-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_alter_blogpost_category"),
        ("members", "0006_alter_userprofile_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="favorite_blogs",
            field=models.ManyToManyField(
                blank=True, related_name="favorited_by", to="blog.blogpost"
            ),
        ),
    ]
