# Generated by Django 5.2.3 on 2025-07-21 11:40

import members.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0007_userprofile_favorite_blogs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to=members.models.user_directory_path
            ),
        ),
    ]
